---
- hosts: localhost
  gather_facts: no
  tasks:
    - ec2_asg:
        name: m5-asg
        load_balancers: m5-elb
        target_group_arns: "{{ m5_tg.target_group_arn }}"
        availability_zones: us-west-1
        launch_template:
            version: '14'
            launch_template_name: image-gallery-lt
            launch_template_id: lt-0268f5db48d28da85
        min_size: 2
        max_size: 4
        desired_capacity: 2
        vpc_zone_identifier: "{{ public_subnet.subnet.id }}"
