---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NAT gateway
      ec2_vpc_nat_gateway:
        name: M5 NAT gateway
        state: present
        subnet_id: "{{ public_subnet.subnet.id }}"
        wait: yes
        region: us-west-1
        if_exist_do_not_create: true
      register: m5_nat_gateway
