---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Module 5.1
      ec2:
        key_name: auburnec2
        group: Module5-developer-sg
        instance_type: t2.micro
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module 5.1
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module 5.1
    - name: Module 5.2
      ec2:
        key_name: auburnec2
        group: Module5-developer-sg
        instance_type: t2.micro
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module 5.2
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module 5.2
