---
- hosts: m5-ans-devel
  gather_facts: no
  tasks:
    - name: Create a new database with name "m5_image_gallery"
      postgresql_db:
        name: m5_image_gallery
        state: present
    - name: Create image_gallery user
      postgresql_query:
        db: m5_image_gallery
        login_user: postgres
        login_password: postgres
        query: CREATE USER image_gallery LOGIN PASSWORD 'simple';
    - name: Create users table if not exists
      postgresql_query:
        db: m5_image_gallery
        login_user: image_gallery
        login_password: "{{ lookup('aws_secret', 'sec-ig-image_gallery') }}"
        query: CREATE TABLE users ( username varchar(200) PRIMARY KEY, password varchar(200), full_name varchar(200));
  # pip: name=psycopg2
    # - name: Ensure the PostgreSQL service is running
    #     service: name=postgresql state=started enabled=yes
