---
- hosts: localhost
  gather_facts: no
  tasks:
    - rds:
        command: create
        instance_name: m5-rds
        db_engine: postgres
        region: us-west-1
        subnet: "{{ rds_sng.subnet_group.id }}"
        vpc_security_groups: m5_sg_postgres
        size: 10
        instance_type: db.t2.micro
        username: postgres
        password: postgres
        tags:
          Module: 5
