---
- hosts: localhost
  gather_facts: no
  tasks:
    - rds:
        command: create
        instance_name: m5-rds
        db_engine: postgres
        db_name: image_gallery
        region: us-west-1
        subnet: m5-rds-sng
        size: "10"
        instance_type: db.t2.micro
        vpc_security_groups: "{{ m5_sg_postgres.group_id }}"
        username: postgres
        password: postgres
        tags:
          Module: 5
        wait: yes
        wait_timeout: 900
    - local_action:
      module: rds
      command: restore
      instance_name: m5-rds
      region: us-west-1
      snapshot: rds:image-gallery-2020-06-28-12-20
