---
- hosts: localhost
  gather_facts: no
  tasks:
    - rds:
        command: create
        instance_name: m5-rds
        db_engine: postgres
        region: us-west-1
        subnet: m5-rds-sng
        size: 10
        instance_type: db.t2.micro
        username: postgres
        password: postgres
        tags:
          Module: 5
        wait: yes
        wait_timeout: 900
    - local_action:
       module: rds
       command: modify
       instance_name: m5-rds
       region: us-west-1
       vpc_security_groups: "{{ vpc.vpc.id }}"
