---
- hosts: localhost
  gather_facts: no
  # vars:
  #   pg_secret: {
  #      "username": "image_gallery",
  #      "password": "simple",
  #      "engine": "postgres",
  #      "host": "{{ rds.instance.endpoint }}",
  #      "port": 5432,
  #      "dbInstanceIdentifier": "m5-rds",
  #      }
  tasks:
    - rds:
        command: create
        instance_name: m5-rds-2
        db_engine: postgres
        db_name: m5_image_gallery
        region: us-west-1
        subnet: m5-rds-sng
        size: "20"
        instance_type: db.t2.micro
        username: postgres
        password: postgres
        tags:
          Module: 5
        wait: yes
        wait_timeout: 900
    - local_action:
        module: rds
        command: restore
        snapshot: ig-ss-2
        instance_name: m5-rds-2
        region: us-west-1
        vpc_security_groups: "{{ m5_sg_postgres.group_id }}"
