---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create security group sg_postgres
      ec2_group:
        name: m5_sg_postgres
        description: sg with all ports necessary
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-west-1
        rules:
          - proto: tcp
            ports:
            - 80
            - 443
            - 1024-65535
            cidr_ip: 0.0.0.0/0
            group_name: m5_sg_postgres
        group_id: m5_sg_postgres
