---
- hosts: localhost
  gather_facts: no
  tasks:
    - rds:
      command: create
      instance_name: m5-rds
      db_engine: postgres
      subnet:
        - "{{ private_subnet1.subnet.id }}"
        - "{{ private_subnet2.subnet.id }}"
      size: 10
      instance_type: db.t2.micro
      username: postgres
      password: postgres
      tags:
        Module: 5
      state: present
