---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create elb target group
      elb_target_group:
        stickiness_type: source_ip
        stickiness_enabled: no
        name: m5-tg
        protocol: tcp
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
      register: m5_tg
    - elb_network_lb:
        name: m5-elb
        scheme: internet-facing
        subnet_mappings:
          - SubnetId: "{{ public_subnet.subnet.id }}"
        listeners:
          - Protocol: TLS
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupName: m5-tg
            Certificates:
              - CertificateArn: "arn:aws:acm:us-west-1:059286676639:certificate/f34b001d-af0c-4b92-a198-0656a7958b84"
        tags:
          Module: 5
        wait: yes
        state: present
