---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: m5-ans-devel
      ec2:
        key_name: cpsc4973
        group: m5_sg_postgres
        instance_type: t2.micro
        image: "{{ ami_id }}"
        instance_tags:
          Name: m5-ans-devel
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        user_data: "{{ lookup('file', './ec2-ans-devel/ec2-prod-ans-bootstrap.sh') }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: m5-ans-devel
      register: dev_ec2
    - name: Add dev ec2 host to hosts list
        add_host:
          hostname: "{{ dev_ec2.name }}"
          groups: dev_ec2
