---
all:
  hosts:
    ec2-54-215-184-171.us-west-1.compute.amazonaws.com:
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python
    ec2-18-144-65-104.us-west-1.compute.amazonaws.com:
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python
